server:
 port: 8000

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/hrms?useSSL=false
  username: root
  password: 12345
 jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate:
   ddl-auto: update
 mail:
  host: smtp.gmail.com
  port: 587
  username: baranwal.adi@gmail.com
  password: ubow uuaj uqir bpys
  protocol: smtp
  debug: true
  test-connection: false
  default-encoding: UTF-8
  properties.mail.smtp.auth: true
  properties.mail.smtp.starttls.enable: true